<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>NeoLauncher</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net10.0</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <None Remove="NeoLauncher.Scripts.neoBridge.js" />
    <EmbeddedResource Include="NeoLauncher.Scripts.neoBridge.js" LogicalName="NeoLauncher.Scripts.neoBridge.js" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Microsoft.WinUI">
      <HintPath>../lanzado/lib/app/Microsoft.WinUI.dll</HintPath>
    </Reference>
    <Reference Include="WinRT.Runtime">
      <HintPath>../lanzado/lib/app/WinRT.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.InteractiveExperiences.Projection">
      <HintPath>../lanzado/lib/app/Microsoft.InteractiveExperiences.Projection.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Windows.SDK.NET">
      <HintPath>../lanzado/lib/app/Microsoft.Windows.SDK.NET.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Web.WebView2.Core.Projection">
      <HintPath>../lanzado/lib/app/Microsoft.Web.WebView2.Core.Projection.dll</HintPath>
    </Reference>
    <Reference Include="System.Management">
      <HintPath>../lanzado/lib/app/System.Management.dll</HintPath>
    </Reference>
    <Reference Include="Velopack">
      <HintPath>../lanzado/lib/app/Velopack.dll</HintPath>
    </Reference>
    <Reference Include="BuildPatchServices">
      <HintPath>../lanzado/lib/app/BuildPatchServices.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Windows.ApplicationModel.Resources.Projection">
      <HintPath>../lanzado/lib/app/Microsoft.Windows.ApplicationModel.Resources.Projection.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Extensions.DependencyInjection.Abstractions">
      <HintPath>../lanzado/lib/app/Microsoft.Extensions.DependencyInjection.Abstractions.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Extensions.DependencyInjection">
      <HintPath>../lanzado/lib/app/Microsoft.Extensions.DependencyInjection.dll</HintPath>
    </Reference>
    <Reference Include="CommunityToolkit.WinUI.Controls.OpacityMaskView">
      <HintPath>../lanzado/lib/app/CommunityToolkit.WinUI.Controls.OpacityMaskView.dll</HintPath>
    </Reference>
    <Reference Include="NuGet.Versioning">
      <HintPath>../lanzado/lib/app/NuGet.Versioning.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>