using System;
using System.CodeDom.Compiler;

namespace Windows.Win32.UI.Input.KeyboardAndMouse;

[Flags]
[GeneratedCode("Microsoft.Windows.CsWin32", "0.3.269+368685089b.RR")]
internal enum MOUSE_EVENT_FLAGS : uint
{
	MOUSEEVENTF_ABSOLUTE = 0x8000u,
	MOUSEEVENTF_LEFTDOWN = 2u,
	MOUSEEVENTF_LEFTUP = 4u,
	MOUSEEVENTF_MIDDLEDOWN = 0x20u,
	MOUSEEVENTF_MIDDLEUP = 0x40u,
	MOUSEEVENTF_MOVE = 1u,
	MOUSEEVENTF_RIGHTDOWN = 8u,
	MOUSEEVENTF_RIGHTUP = 0x10u,
	MOUSEEVENTF_WHEEL = 0x800u,
	MOUSEEVENTF_XDOWN = 0x80u,
	MOUSEEVENTF_XUP = 0x100u,
	MOUSEEVENTF_HWHEEL = 0x1000u,
	MOUSEEVENTF_MOVE_NOCOALESCE = 0x2000u,
	MOUSEEVENTF_VIRTUALDESK = 0x4000u
}
