using System;
using System.CodeDom.Compiler;

namespace Windows.Win32.System.Threading;

[Flags]
[GeneratedCode("Microsoft.Windows.CsWin32", "0.3.269+368685089b.RR")]
internal enum STARTUPINFOW_FLAGS : uint
{
	STARTF_FORCEONFEEDBACK = 0x40u,
	STARTF_FORCEOFFFEEDBACK = 0x80u,
	STARTF_PREVENTPINNING = 0x2000u,
	STARTF_RUNFULLSCREEN = 0x20u,
	STARTF_TITLEISAPPID = 0x1000u,
	STARTF_TITLEISLINKNAME = 0x800u,
	STARTF_UNTRUSTEDSOURCE = 0x8000u,
	STARTF_USECOUNTCHARS = 8u,
	STARTF_USEFILLATTRIBUTE = 0x10u,
	STARTF_USEHOTKEY = 0x200u,
	STARTF_USEPOSITION = 4u,
	STARTF_USESHOWWINDOW = 1u,
	STARTF_USESIZE = 2u,
	STARTF_USESTDHANDLES = 0x100u
}
