using System;
using System.CodeDom.Compiler;

namespace Windows.Win32.UI.WindowsAndMessaging;

[Flags]
[GeneratedCode("Microsoft.Windows.CsWin32", "0.3.269+368685089b.RR")]
internal enum MESSAGEBOX_STYLE : uint
{
	MB_ABORTRETRYIGNORE = 2u,
	MB_CANCELTRYCONTINUE = 6u,
	MB_HELP = 0x4000u,
	MB_OK = 0u,
	MB_OKCANCEL = 1u,
	MB_RETRYCANCEL = 5u,
	MB_YESNO = 4u,
	MB_YESNOCANCEL = MB_ABORTRETRYIGNORE | MB_OKCANCEL,
	MB_ICONHAND = 0x10u,
	MB_ICONQUESTION = 0x20u,
	MB_ICONEXCLAMATION = MB_ICONHAND | MB_ICONQUESTION,
	MB_ICONASTERISK = 0x40u,
	MB_USERICON = 0x80u,
	MB_ICONWARNING = MB_ICONEXCLAMATION,
	MB_ICONERROR = MB_ICONHAND,
	MB_ICONINFORMATION = MB_ICONASTERISK,
	MB_ICONSTOP = MB_ICONHAND,
	MB_DEFBUTTON1 = 0u,
	MB_DEFBUTTON2 = 0x100u,
	MB_DEFBUTTON3 = 0x200u,
	MB_DEFBUTTON4 = MB_DEFBUTTON2 | MB_DEFBUTTON3,
	MB_APPLMODAL = 0u,
	MB_SYSTEMMODAL = 0x1000u,
	MB_TASKMODAL = 0x2000u,
	MB_NOFOCUS = 0x8000u,
	MB_SETFOREGROUND = 0x10000u,
	MB_DEFAULT_DESKTOP_ONLY = 0x20000u,
	MB_TOPMOST = 0x40000u,
	MB_RIGHT = 0x80000u,
	MB_RTLREADING = 0x100000u,
	MB_SERVICE_NOTIFICATION = 0x200000u,
	MB_SERVICE_NOTIFICATION_NT3X = MB_TOPMOST,
	MB_TYPEMASK = 0xFu,
	MB_ICONMASK = MB_ICONEXCLAMATION | MB_ICONASTERISK | MB_USERICON,
	MB_DEFMASK = 0xF00u,
	MB_MODEMASK = MB_SYSTEMMODAL | MB_TASKMODAL,
	MB_MISCMASK = MB_HELP | MB_NOFOCUS
}
